<!DOCTYPE html>
<html lang="es" style="scroll-behavior: smooth;">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="../../../assets/css/global-styles.css">
	<link rel="stylesheet" type="text/css" href="../../../assets/css/index.css">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
	<title>Razer Headset - TecnoShop</title>
	<style>
		.product-detail-container{max-width:1200px;margin:0 auto;padding:2rem}.product-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:3rem;margin-bottom:3rem}.product-image-container{background:linear-gradient(135deg,rgba(30,41,59,.8) 0%,rgba(30,41,59,.6) 100%);border-radius:20px;padding:2rem;display:flex;align-items:center;justify-content:center;border:1px solid rgba(255,255,255,.1)}.product-image-container img{max-width:100%;height:auto;filter:drop-shadow(0 10px 30px rgba(0,0,0,.3))}.product-info{display:flex;flex-direction:column;justify-content:center}.product-info h1{font-size:2.5rem;margin-bottom:1rem;background:var(--gradient);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.product-badge{display:inline-block;background:var(--gradient);color:#fff;padding:.5rem 1rem;border-radius:20px;font-size:.85rem;font-weight:700;margin-bottom:1rem}.product-price{font-size:2.5rem;color:var(--accent-color);font-weight:700;margin:1rem 0}.product-stock{font-size:1.1rem;color:var(--text-secondary);margin-bottom:1.5rem}.product-description{font-size:1.1rem;color:var(--text-secondary);line-height:1.8;margin-bottom:2rem}.specs-list{background:rgba(30,41,59,.5);border-radius:16px;padding:1.5rem;margin-bottom:2rem}.specs-list h3{color:var(--text-primary);margin-bottom:1rem;font-size:1.3rem}.specs-list ul{list-style:none;padding:0}.specs-list li{color:var(--text-secondary);padding:.5rem 0;border-bottom:1px solid rgba(255,255,255,.1);font-size:1rem}.specs-list li:last-child{border-bottom:none}.specs-list li::before{content:"✓ ";color:var(--accent-color);font-weight:700;margin-right:.5rem}@media (max-width:768px){.product-detail-grid{grid-template-columns:1fr}.product-info h1{font-size:2rem}.product-price{font-size:2rem}}
	</style>
</head>
<body>
	<header class="header"><nav class="navbar"><div class="logo"><h1 onclick="location.href='../../../index.php'" style="cursor:pointer">💻 Tecno<span class="accent">Shop</span></h1></div><div class="nav-links"><a href="../../../index.php" class="nav-link">Inicio</a><a href="../../client/catalogo_computadoras.php" class="nav-link">Computadoras</a><a href="../../client/catalogo_piezas.php" class="nav-link">Componentes</a><a href="../../client/login.php" class="nav-link-btn">Iniciar Sesión</a></div></nav></header>
	<div class="product-detail-container"><div class="product-detail-grid"><div class="product-image-container"><img src="../../../assets/images/parts/Razer Headset.png" alt="Razer Headset"></div><div class="product-info"><span class="product-badge">7.1 SURROUND</span><h1>Razer Headset</h1><p class="product-price">$950</p><p class="product-stock">📦 Stock disponible: 15 unidades</p><p class="product-description">Audífonos gaming con sonido envolvente 7.1 virtual. Sumérgete completamente en tus juegos favoritos.</p><div class="specs-list"><h3>🎧 Especificaciones Técnicas</h3><ul><li>Drivers: 50mm personalizados</li><li>Frecuencia: 12Hz - 28kHz</li><li>Micrófono: Retráctil con cancelación de ruido</li><li>Conectividad: USB y 3.5mm</li><li>Iluminación: Razer Chroma RGB</li><li>Compatibilidad: PC, PS4, Xbox, Switch</li></ul></div><button class="btn btn-primary" onclick="location.href='../../client/catalogo_piezas.php'" style="width:100%">← Volver al Catálogo</button></div></div></div>
	<footer class="footer"><div class="container"><div class="footer-content"><div class="footer-section"><h3>💻 TecnoShop</h3><p>Tu tienda de confianza en tecnología</p></div><div class="footer-section"><h4>Enlaces Rápidos</h4><a href="../../../index.php">Inicio</a><a href="../../client/catalogo_computadoras.php">Computadoras</a><a href="../../client/catalogo_piezas.php">Componentes</a></div><div class="footer-section"><h4>Contacto</h4><p>📧 info@tecnoshop.com</p><p>📱 (555) 123-4567</p></div></div><div class="footer-bottom"><p>&copy; 2025 TecnoShop. Todos los derechos reservados.</p></div></div></footer>
</body>
</html>
